CREATE TABLE EXPORT (
    ID BIGSERIAL PRIMARY KEY,
    TYP TEXT NOT NULL,
    STATUS TEXT NOT NULL,
    BETRIEBSNUMMER TEXT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY TEXT,
    UPDATED_AT TIMESTAMP WITH TIME ZONE,
    UPDATED_BY TEXT
);

CREATE TABLE EXPORT_EVENT (
    ID UUID PRIMARY KEY,
    EXPORT_ID BIGINT NOT NULL,
    TYPE TEXT NOT NULL,
    DETAILS TEXT,
    TRACE_ID TEXT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY TEXT,
    VERSION BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT FK_EXPORT_EVENT_EXPORT FOREIGN KEY (EXPORT_ID) REFERENCES EXPORT(ID)
);

CREATE TABLE DEUEV_ANMELDUNG (
    MELDECENTER_ID UUID PRIMARY KEY,
    MELDUNG_ID UUID NOT NULL,
    MELDUNG_TYP TEXT NOT NULL,
    MELDUNG_QUELLE TEXT NOT NULL,
    MELDUNG_MANDANT_ID TEXT NOT NULL,
    MELDUNG_ERSTELLT_AM TIMESTAMP WITH TIME ZONE NOT NULL,
    ARBEITGEBER_BETRIEBSNUMMER TEXT NOT NULL,
    MITARBEITER_ID TEXT NOT NULL,
    MITARBEITER_VORNAME TEXT NOT NULL,
    MITARBEITER_NACHNAME TEXT NOT NULL,
    MITARBEITER_GEBURTSDATUM DATE NOT NULL,
    MITARBEITER_SOZIALVERSICHERUNGSNUMMER TEXT NOT NULL,
    MITARBEITER_ANSCHRIFT_STRASSE TEXT NOT NULL,
    MITARBEITER_ANSCHRIFT_PLZ TEXT NOT NULL,
    MITARBEITER_ANSCHRIFT_ORT TEXT NOT NULL,
    MITARBEITER_KONTAKT_EMAIL TEXT NOT NULL,
    MITARBEITER_KONTAKT_TELEFON_PRAEFIX TEXT NOT NULL,
    MITARBEITER_KONTAKT_TELEFON_VORWAHL TEXT NOT NULL,
    MITARBEITER_KONTAKT_TELEFON_NUMMER TEXT NOT NULL,
    BESCHAEFTIGUNG_BEGINN DATE NOT NULL,
    BESCHAEFTIGUNG_BESCHAEFTIGUNGSART TEXT NOT NULL,
    AUDIT_CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    AUDIT_CREATED_BY TEXT,
    AUDIT_UPDATED_AT TIMESTAMP WITH TIME ZONE,
    AUDIT_UPDATED_BY TEXT,
    EXPORT_ID BIGINT,
    VERSION BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT FK_DEUEV_ANMELDUNG_EXPORT FOREIGN KEY (EXPORT_ID) REFERENCES EXPORT(ID)
);

CREATE TABLE ENTGELTBESCHEINIGUNG_AU (
    MELDECENTER_ID UUID PRIMARY KEY,
    MELDUNG_ID UUID NOT NULL,
    MELDUNG_TYP TEXT NOT NULL,
    MELDUNG_QUELLE TEXT NOT NULL,
    MELDUNG_MANDANT_ID TEXT NOT NULL,
    MELDUNG_ERSTELLT_AM TIMESTAMP WITH TIME ZONE NOT NULL,
    ARBEITGEBER_BETRIEBSNUMMER TEXT NOT NULL,
    MITARBEITER_ID TEXT NOT NULL,
    MITARBEITER_VORNAME TEXT NOT NULL,
    MITARBEITER_NACHNAME TEXT NOT NULL,
    MITARBEITER_GEBURTSDATUM DATE NOT NULL,
    MITARBEITER_SOZIALVERSICHERUNGSNUMMER TEXT NOT NULL,
    MITARBEITER_ANSCHRIFT_STRASSE TEXT NOT NULL,
    MITARBEITER_ANSCHRIFT_PLZ TEXT NOT NULL,
    MITARBEITER_ANSCHRIFT_ORT TEXT NOT NULL,
    MITARBEITER_KONTAKT_EMAIL TEXT NOT NULL,
    MITARBEITER_KONTAKT_TELEFONNUMMER TEXT NOT NULL,
    MITARBEITER_KONTAKT_BEVORZUGTE_KONTAKTSART TEXT NOT NULL,
    KRANKHEIT_ARBEITSUNFAEHIGKEIT_BEGINN DATE NOT NULL,
    KRANKHEIT_ARBEITSUNFAEHIGKEIT_ENDE DATE NOT NULL,
    ENTGELT_BEZUGSZEITRAUM TEXT NOT NULL,
    ENTGELT_BRUTTOENTGELT DECIMAL(19, 2) NOT NULL,
    AUDIT_CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    AUDIT_CREATED_BY TEXT,
    AUDIT_UPDATED_AT TIMESTAMP WITH TIME ZONE,
    AUDIT_UPDATED_BY TEXT,
    EXPORT_ID BIGINT,
    VERSION BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT FK_ENTGELTBESCHEINIGUNG_AU_EXPORT FOREIGN KEY (EXPORT_ID) REFERENCES EXPORT(ID)
);

-- Placeholder Export mit ID=1
INSERT INTO EXPORT (TYP, STATUS, BETRIEBSNUMMER, CREATED_AT, CREATED_BY)
VALUES ('MELDUNG', 'DUPLICATES', '00000000',  NOW(), 'SYSTEM');
